version: "3.8"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "test"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
  postgres1:
    image: postgres:latest
    environment:
      POSTGRES_DB: "test1"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
